language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

# NOTE: When we break out the unit tests from the actual python modules this is
#       going to break this script statement.
script:
    - pip install . && pip install -r tests_require && python -m pytest bzlib
